global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "assesspro-backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend.assesspro.svc.cluster.local:5001"]
